### ISSUE TITLE
Set up account for Kathy on GLCWRA jump server

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/GBRA#9]
She will need credentials to start and access the server.

kdooley@contractor.usgs.gov

**Comment by lprivette** [comment]
Kathy sucessfully logged into AWS, but after navigating to EC2 > instances > she cannot see the GLCWRA jump server or any other instances.

![image](https://user-images.githubusercontent.com/23640741/70571264-7ebd3080-1b6b-11ea-8b95-3d068edebcd5.png)

Does she need to be added to a certain security group?

**Comment by aaronstephenson** [comment]
OK, I modified her permissions to be exactly the same as Chris Sanocki's.

**Comment by aaronstephenson** [comment]
Also, I just realized that you're looking in the Ohio region, where we don't have any assets. Change the region to N. Virginia and you should see all the instances.

**Comment by lprivette** [comment]
Doh! I always forget to check the region. Thank you Aaron!

Success with AWS start up and server access.
